path_classifiers:
  test:
    - "**/*.test.js"
  library:
    - exclude: "packages/node_modules/@enocean-js/"
  main:
    - include: "packages/node_modules/@enocean-js/"
queries:
  - exclude: "resources/"
  - include: "packages/node_modules/@enocean-js/"
  tags:
    - "main"
